### PR TITLE
First pass at integrating art

### LINKED ISSUE #167: Integrate the art assets cleanly into the game
Use the exported assets drawn by our artist @Asmo99, but also Krita and the batch export addon to improve the game's visuals in Godot. Some assets may need cleanup, to be resized... Get in touch with me if you need anything there.

I put some assets into the game already, but there are:

1. Some assets missing
2. Some assets don't properly tile

## To add

- [x] Checkpoint
- [x] Hooking point
- [x] Portal
- [ ] The first monsters, the flying fish and shielded monster. Attach the fish/bird-like monster sprite to the Charger monster scene.
- [x] Final sprite for Robi, the main character. Test `robi_shaded.png` to see if it works well. **Do not** integrate the full cutout character yet.

## To refine

Background assets, i.e. the mountains, sky, and cloud.

- [x] The sky could be replaced by a gradient texture in Godot, while the mountains should cleanly tile.
- [x] Ensure the background's parallax works well and the edges of the mountains don't get in the view.

## To review

The background assets need review, especially the ones in the `props` directory won't work well in my opinion. They are not as polished as the other sprites, have a somewhat different style, more textured, and more importantly, their format won't work well for level design. We might need to scrap or redo them.

### PR DESCRIPTION
**Pull request by razcore-art**
- replaced object/enemy bodies with provided art:
  - checkpoint
  - hooking
  - points
  - portals
  - final Robi sprite (`roby_shaded.png`)
  - sky (with gradient texture)
- reworked mountains to scroll seamless & increase width of
  texture
- reworked Arael's tileset (there was a small 1 pixel gap in some tiles)
- integrate props (trees, rocks, roots, bushes)

closes #167

*note* this has breaking changes because some `.tscn` files were reworked so resources changed IDs

### CODE REVIEW

**Comment by razcore-art** [comment]
I couldn't find these fish monster assets that you mentioned. There's a funny looking shield-like monster, but not the fish/bird things.

**Comment by NathanLovato** [comment]
Seems we don't have a finished version of the fish monster. It's okay, forget it for now.

**Comment by NathanLovato** [comment]
For now the art looks pretty bad together, it may look better with the environment art changed for Asmo's tileset and adding a tree or two, I dunno

**Comment by NathanLovato** [comment]
Just checked, seems to be working, but did you recolor the background props? They're too bright. Also, there was no need to place a lot of them on the test scene, this one is going away. The roots, rocks, bushes are also way too rough, they need to be refined a lot.

What do you think of Robi's look? It fits better now but I still think there's something funny about it.

**Comment by razcore-art** [comment]
So I didn't recolor anything, but I did change Arael's tileset to RGBA 8bit, it was 16bit and in Godot, at least at my end it was showing very bright. Changing it to 8bit corrected the brightness.

This is how it looks at my end, in the editor. I'd have to recompile the Heatmap to make it run in game so don't know if there's any difference between in-editor and in-game.

image

About Robi, I'm not sure, it might be the proportions, they're different from the unshaded version, he's a bit wider I think.

**Pull request merged**
